AWSTemplateFormatVersion: 2010-09-09
Description: Laboratorio Cloudging LA SAS

Parameters:
  VPCId:
    Description: Nombre de la llave SSH de la EC2
    Type: AWS::EC2::VPC::Id
  VPCCidr:
    Description:  Direccion IP de la VPC
    Type: String
    Default: 10.0.0.0/16
  PublicSubnets:
    Description: Seleccione las 2 subredes publicas
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnets:
    Description: Seleccione las 2 subredes privadas
    Type: List<AWS::EC2::Subnet::Id>
  KeyName: 
    Description: Nombre de la llave SSH de la EC2
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "aamirKP1"
  Ec2AmiId:
    Description: Seleccione la AMI, utilice AMI Linux 2
    Type: String
    Default: "ami-074cce78125f09d61"


Resources:
  EfsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudinglab.s3.us-west-2.amazonaws.com/efs.yml"
      TimeoutInMinutes: 30
      Parameters: 
        PrivateSubnetId1: !Select [ 0, !Ref PrivateSubnets ]
        PrivateSubnetId2: !Select [ 1, !Ref PrivateSubnets ]
        VPCId: !Ref VPCId
        VPCCidr: !Ref VPCCidr

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudinglab.s3.us-west-2.amazonaws.com/alb.yml"
      TimeoutInMinutes: 30
      Parameters: 
        VPCId: !Ref VPCId
        PublicSubnets: !Join [",", !Ref PublicSubnets]

  AutoScallingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - RDS
      - LoadBalancerStack
      - EfsStack
    Properties: 
      TemplateURL: "https://cloudinglab.s3.us-west-2.amazonaws.com/asg.yml"
      TimeoutInMinutes: 30
      Parameters: 
        Ec2AmiId: !Ref Ec2AmiId
        KeyName: !Ref KeyName
        PrivateSubnets: !Join [",", !Ref PrivateSubnets]
        VPCId: !Ref VPCId
        VPCCidr: !Ref VPCCidr

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudinglab.s3.us-west-2.amazonaws.com/rds.yml"
      TimeoutInMinutes: 30
      Parameters:
        VPCId: !Ref VPCId
        VPCCidr: !Ref VPCCidr
        PrivateSubnets: !Join [",", !Ref PrivateSubnets]